db.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
db.url=jdbc:log4jdbc:mariadb://solfood.cbcsswkcyvee.ap-northeast-2.rds.amazonaws.com:3306/sol
db.username=SSud
db.password=55688789

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true

# Server Configuration
server.ip=localhost
server.port=8090

# Kakao Configuration
kakao.restApiKey=5d4b8480ccbf31d3c2c6cca2fae79fd6
kakao.jsApiKey=8f9034d6cf1da650e02b54751e02fcb3

#iamport
imp.code=imp65305268
imp.api.key=4261574202603267
imp.api.secretkey=P5KNe2lRs3bTPf2gZcwq9mENf9VTpraYR2gHhNftQaLHn8WUipOHO1lscJJMwazhpLNK1zEIZJmQN1vV

# AWS S3 Configuration
aws.s3.bucket=sol-food-bucket
aws.s3.region=ap-northeast-2
aws.access.key=AKIAXWMA6EDHNEDF5IGH
aws.secret.key=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

# Google Analytics
ga4.property-id=462237129
ga4.key-path=classpath:goyo-415004-a06976a1469f.json